version: '3'
services:
  mkdocs:
    build:
      context: ./documentacao
    ports:
      - "8000:8000"
    working_dir: /app
    command: mkdocs serve --dev-addr=0.0.0.0:8000

  react:
    build:
      context: ./front
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run dev

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - mkdocs
